### ISSUE TITLE
work

### ISSUE THREAD

**Issue by juev** [kshmatov/emacs.d#1]
Привет!

Это получается, что ты используешь emacs для программирования? Как интересно.
То есть не vscode или golang, как многие, а именно emacs??

**Comment by kshmatov** [comment]
И его тоже.
Есть у меня мелкий ноут который с собой таскаю в поездки, там памяти мало. Вот на нем и пишу в emacs. Сейчас еще пытаюсь вим освоить, с ним можно везде одинаковую раскладку хоткеев сделать, не надо будет помнить где что.

**Comment by juev** [comment]
Понял, спасибо! :)
